# Generated by Django 5.1.7 on 2025-03-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprofile',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef')], max_length=20, unique=True),
        ),
    ]
