# Generated by Django 5.1.7 on 2025-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprofile',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef')], max_length=20),
        ),
    ]
