# Generated by Django 5.1.7 on 2025-04-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mentorstudentmapping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='preferred_criteria',
            field=models.TextField(blank=True, help_text='Preferred criteria for AI evaluation.', null=True),
        ),
    ]
