# Generated by Django 5.1.7 on 2025-04-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assessment_preferred_criteria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef')], default='codeforces', help_text='The platform hosting this question.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest_id',
            field=models.IntegerField(blank=True, help_text='Codeforces Contest ID (e.g., 1998). Leave blank for CodeChef.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='problem_index',
            field=models.CharField(help_text="Platform-specific Problem Index/Code (e.g., 'B', 'A1', 'START01').", max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, help_text='Problem title (fetched from platform)', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('platform', 'codeforces')), fields=('assessment', 'platform', 'contest_id', 'problem_index'), name='unique_assessment_codeforces_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('platform', 'codechef')), fields=('assessment', 'platform', 'problem_index'), name='unique_assessment_codechef_question'),
        ),
    ]
