# Generated by Django 5.1.7 on 2025-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_unique_together_question_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='plagiarism_score',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated plagiarism score (e.g., 0-100), if available.', null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='submitted_code',
            field=models.TextField(blank=True, help_text='The source code submitted by the student.', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='codeforces_passed_test_count',
            field=models.IntegerField(blank=True, help_text='Number of tests passed', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='codeforces_submission_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the evaluated platform submission', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='codeforces_verdict',
            field=models.CharField(blank=True, help_text='Verdict from Platform (e.g., AC, WA, TLE)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='evaluation_feedback',
            field=models.TextField(blank=True, help_text='Feedback from evaluation', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='evaluation_score',
            field=models.FloatField(blank=True, help_text='Score (0-100) based on verdict/tests/AI', null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='solved_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when the question was successfully solved (verdict='AC')", null=True),
        ),
    ]
